DROP TABLE "SET2DB"."USER_ROLE_MAPPING";
DROP TABLE "SET2DB"."ROLE";
DROP SEQUENCE auto_seq;

CREATE TABLE "SET2DB"."ROLE" ("ROLE_ID" NUMBER(19,0) NOT NULL ENABLE, "ROLE_NAME" VARCHAR2(255 CHAR), "STATUS" VARCHAR2(255 CHAR), "IS_ACTIVE" NUMBER(1,0), PRIMARY KEY ("ROLE_ID"));
   
INSERT INTO "SET2DB"."ROLE" (ROLE_ID, ROLE_NAME, STATUS, IS_ACTIVE) VALUES (1, 'ACCOUNT_MANAGER', 'TRUE', 1);
INSERT INTO "SET2DB"."ROLE" (ROLE_ID, ROLE_NAME, STATUS, IS_ACTIVE) VALUES(2, 'PROJECT_MANAGER', 'TRUE', 1);
INSERT INTO "SET2DB"."ROLE" (ROLE_ID, ROLE_NAME, STATUS, IS_ACTIVE) VALUES(3, 'TEAM_LEAD', 'TRUE', 1);
INSERT INTO "SET2DB"."ROLE" (ROLE_ID, ROLE_NAME, STATUS, IS_ACTIVE) VALUES(4, 'MEMBER', 'TRUE', 1);
INSERT INTO "SET2DB"."ROLE" (ROLE_ID, ROLE_NAME, STATUS, IS_ACTIVE) VALUES(5, 'ADMIN', 'TRUE', 1);


CREATE TABLE "SET2DB"."USER_ROLE_MAPPING" ("ID" NUMBER(19,0) , "USER_ID" NUMBER(19,0), "ROLE_ID" NUMBER(19,0), "PROJECT_ID" NUMBER(19,0) DEFAULT NULL, "ACCOUNT_ID" NUMBER(19,0) DEFAULT NULL, "TEAM_ID" NUMBER(19,0) DEFAULT NULL, PRIMARY KEY ("ID") , CONSTRAINT "FK_USER_ID_CONSTRAINT" FOREIGN KEY ("USER_ID") REFERENCES "SET2DB"."EMPLOYEE" ("TCS_EMPLOYEE_ID") , CONSTRAINT "FK_ROLE_ID_CONSTRAINT" FOREIGN KEY ("ROLE_ID") REFERENCES "SET2DB"."ROLE" ("ROLE_ID") , CONSTRAINT "FK_PROJECT_ID_CONSTRAINT" FOREIGN KEY ("PROJECT_ID") REFERENCES "SET2DB"."PROJECT" ("PROJECT_ID"), CONSTRAINT "FK_ACCOUNT_ID_CONSTRAINT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "SET2DB"."ACCOUNT" ("ACC_ID"), CONSTRAINT "FK_TEAM_ID_CONSTRAINT" FOREIGN KEY ("TEAM_ID") REFERENCES "SET2DB"."TEAM" ("TEAM_ID"));

CREATE SEQUENCE auto_seq START WITH 1;

CREATE OR REPLACE TRIGGER AUTO_INCREASE BEFORE INSERT ON USER_ROLE_MAPPING FOR EACH ROW BEGIN SELECT auto_seq.NEXTVAL INTO   :new.id FROM   dual ; END ;;